### ISSUE TITLE
Bazel clean shouldn't be needed

### ISSUE THREAD

**Issue by alexeagle** [gregmagolan/abc-demo-build-with-aot-universal#2]
Why do you bazel clean on each build? If that was needed, then it's a bug, users should not need to do that, makes the build non-incremental. Or was this just out of habit?

**Comment by gregmagolan** [comment]
Mostly out of habit. I was changing the dependent bazel build rules a lot and wasn't sure if Bazel would always handle that. Its a small built as well so doesn't take long to clean and rebuild.

**Comment by alexeagle** [comment]
Yeah I think there might be a bug with local_repository() not picking up
changes, I've seen something like that too. We should try to capture a
minimal repro for the Bazel team. We don't want users to get in the habit
of cleaning.

**Comment by gregmagolan** [comment]
I think I was remember seeing something odd with local_repository() as well which is probably why I put in the forced clean. Updated the build to not do that. Incremental build looks good.
